//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 02:47:31 PM BST 
//


package com.mash.model.catalog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mash.model.catalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Person_QNAME = new QName("http://www.mash.data.com/mashModel", "person");
    private final static QName _Referral_QNAME = new QName("http://www.mash.data.com/mashModel", "referral");
    private final static QName _Participation_QNAME = new QName("http://www.mash.data.com/mashModel", "participation");
    private final static QName _Parent_QNAME = new QName("http://www.mash.data.com/mashModel", "parent");
    private final static QName _Relation_QNAME = new QName("http://www.mash.data.com/mashModel", "relation");
    private final static QName _Crime_QNAME = new QName("http://www.mash.data.com/mashModel", "crime");
    private final static QName _Victim_QNAME = new QName("http://www.mash.data.com/mashModel", "victim");
    private final static QName _SubjectOf_QNAME = new QName("http://www.mash.data.com/mashModel", "subjectOf");
    private final static QName _Sibiling_QNAME = new QName("http://www.mash.data.com/mashModel", "sibiling");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mash.model.catalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Sibiling }
     * 
     */
    public Sibiling createSibiling() {
        return new Sibiling();
    }

    /**
     * Create an instance of {@link Crime }
     * 
     */
    public Crime createCrime() {
        return new Crime();
    }

    /**
     * Create an instance of {@link Victim }
     * 
     */
    public Victim createVictim() {
        return new Victim();
    }

    /**
     * Create an instance of {@link SubjectOf }
     * 
     */
    public SubjectOf createSubjectOf() {
        return new SubjectOf();
    }

    /**
     * Create an instance of {@link Participations }
     * 
     */
    public Participations createParticipations() {
        return new Participations();
    }

    /**
     * Create an instance of {@link Household }
     * 
     */
    public Household createHousehold() {
        return new Household();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "person")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Referral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "referral")
    public JAXBElement<Referral> createReferral(Referral value) {
        return new JAXBElement<Referral>(_Referral_QNAME, Referral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Participation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "participation")
    public JAXBElement<Participation> createParticipation(Participation value) {
        return new JAXBElement<Participation>(_Participation_QNAME, Participation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "parent", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "relation")
    public JAXBElement<Parent> createParent(Parent value) {
        return new JAXBElement<Parent>(_Parent_QNAME, Parent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Relation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "relation")
    public JAXBElement<Relation> createRelation(Relation value) {
        return new JAXBElement<Relation>(_Relation_QNAME, Relation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Crime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "crime")
    public JAXBElement<Crime> createCrime(Crime value) {
        return new JAXBElement<Crime>(_Crime_QNAME, Crime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Victim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "victim", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "participation")
    public JAXBElement<Victim> createVictim(Victim value) {
        return new JAXBElement<Victim>(_Victim_QNAME, Victim.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "subjectOf", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "participation")
    public JAXBElement<SubjectOf> createSubjectOf(SubjectOf value) {
        return new JAXBElement<SubjectOf>(_SubjectOf_QNAME, SubjectOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sibiling }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "sibiling", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "relation")
    public JAXBElement<Sibiling> createSibiling(Sibiling value) {
        return new JAXBElement<Sibiling>(_Sibiling_QNAME, Sibiling.class, null, value);
    }

}
