//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.03 at 01:40:44 PM BST 
//


package com.mash.model.catalog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mash.model.catalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Referral_QNAME = new QName("http://www.mash.data.com/mashModel", "referral");
    private final static QName _Crime_QNAME = new QName("http://www.mash.data.com/mashModel", "crime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mash.model.catalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link Crime }
     * 
     */
    public Crime createCrime() {
        return new Crime();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Act }
     * 
     */
    public Act createAct() {
        return new Act();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Referral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "referral")
    public JAXBElement<Referral> createReferral(Referral value) {
        return new JAXBElement<Referral>(_Referral_QNAME, Referral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Crime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "crime")
    public JAXBElement<Crime> createCrime(Crime value) {
        return new JAXBElement<Crime>(_Crime_QNAME, Crime.class, null, value);
    }

}
