//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.02 at 01:06:53 PM GMT 
//


package com.mash.model.catalog;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mash.model.catalog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ActSummary_QNAME = new QName("http://www.mash.data.com/mashModel", "actSummary");
    private final static QName _Person_QNAME = new QName("http://www.mash.data.com/mashModel", "person");
    private final static QName _EntitySummary_QNAME = new QName("http://www.mash.data.com/mashModel", "entitySummary");
    private final static QName _Act_QNAME = new QName("http://www.mash.data.com/mashModel", "act");
    private final static QName _Referral_QNAME = new QName("http://www.mash.data.com/mashModel", "referral");
    private final static QName _Participation_QNAME = new QName("http://www.mash.data.com/mashModel", "participation");
    private final static QName _Generic_QNAME = new QName("http://www.mash.data.com/mashModel", "generic");
    private final static QName _Entity_QNAME = new QName("http://www.mash.data.com/mashModel", "entity");
    private final static QName _SubjectOf_QNAME = new QName("http://www.mash.data.com/mashModel", "subjectOf");
    private final static QName _Location_QNAME = new QName("http://www.mash.data.com/mashModel", "location");
    private final static QName _Crime_QNAME = new QName("http://www.mash.data.com/mashModel", "crime");
    private final static QName _Victim_QNAME = new QName("http://www.mash.data.com/mashModel", "victim");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mash.model.catalog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActSummary }
     * 
     */
    public ActSummary createActSummary() {
        return new ActSummary();
    }

    /**
     * Create an instance of {@link SubjectOf }
     * 
     */
    public SubjectOf createSubjectOf() {
        return new SubjectOf();
    }

    /**
     * Create an instance of {@link GenericParticipant }
     * 
     */
    public GenericParticipant createGenericParticipant() {
        return new GenericParticipant();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Persons }
     * 
     */
    public Persons createPersons() {
        return new Persons();
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link Entities }
     * 
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link Locations }
     * 
     */
    public Locations createLocations() {
        return new Locations();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Crime }
     * 
     */
    public Crime createCrime() {
        return new Crime();
    }

    /**
     * Create an instance of {@link Victim }
     * 
     */
    public Victim createVictim() {
        return new Victim();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Participations }
     * 
     */
    public Participations createParticipations() {
        return new Participations();
    }

    /**
     * Create an instance of {@link Occupant }
     * 
     */
    public Occupant createOccupant() {
        return new Occupant();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Household }
     * 
     */
    public Household createHousehold() {
        return new Household();
    }

    /**
     * Create an instance of {@link SystemId }
     * 
     */
    public SystemId createSystemId() {
        return new SystemId();
    }

    /**
     * Create an instance of {@link Marker }
     * 
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "actSummary", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "act")
    public JAXBElement<ActSummary> createActSummary(ActSummary value) {
        return new JAXBElement<ActSummary>(_ActSummary_QNAME, ActSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "person", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "entity")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitySummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "entitySummary", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "entity")
    public JAXBElement<EntitySummary> createEntitySummary(EntitySummary value) {
        return new JAXBElement<EntitySummary>(_EntitySummary_QNAME, EntitySummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Act }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "act")
    public JAXBElement<Act> createAct(Act value) {
        return new JAXBElement<Act>(_Act_QNAME, Act.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Referral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "referral", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "act")
    public JAXBElement<Referral> createReferral(Referral value) {
        return new JAXBElement<Referral>(_Referral_QNAME, Referral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Participation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "participation")
    public JAXBElement<Participation> createParticipation(Participation value) {
        return new JAXBElement<Participation>(_Participation_QNAME, Participation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericParticipant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "generic", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "participation")
    public JAXBElement<GenericParticipant> createGeneric(GenericParticipant value) {
        return new JAXBElement<GenericParticipant>(_Generic_QNAME, GenericParticipant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Entity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "entity")
    public JAXBElement<Entity> createEntity(Entity value) {
        return new JAXBElement<Entity>(_Entity_QNAME, Entity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectOf }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "subjectOf", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "participation")
    public JAXBElement<SubjectOf> createSubjectOf(SubjectOf value) {
        return new JAXBElement<SubjectOf>(_SubjectOf_QNAME, SubjectOf.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "location", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "entity")
    public JAXBElement<Location> createLocation(Location value) {
        return new JAXBElement<Location>(_Location_QNAME, Location.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Crime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "crime", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "act")
    public JAXBElement<Crime> createCrime(Crime value) {
        return new JAXBElement<Crime>(_Crime_QNAME, Crime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Victim }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mash.data.com/mashModel", name = "victim", substitutionHeadNamespace = "http://www.mash.data.com/mashModel", substitutionHeadName = "participation")
    public JAXBElement<Victim> createVictim(Victim value) {
        return new JAXBElement<Victim>(_Victim_QNAME, Victim.class, null, value);
    }

}
